# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt /app/
RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir -r /app/requirements.txt

# Copy rest of the project
COPY . /app/

CMD ["gunicorn", "office_empo_proj.wsgi:application", "--bind", "0.0.0.0:8000"]
